"""Adding password reset

Revision ID: e567f0696f7f
Revises: f0160140d255
Create Date: 2023-05-07 10:31:41.251010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e567f0696f7f'
down_revision = 'f0160140d255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_sent_at')
    op.drop_column('users', 'reset_hash')
    # ### end Alembic commands ###
