"""Adding account activation

Revision ID: f0160140d255
Revises: bbd92e12abc6
Create Date: 2023-05-07 09:15:44.871405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0160140d255'
down_revision = 'bbd92e12abc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('activation_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('activation_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_sent_at')
    op.drop_column('users', 'activation_hash')
    op.drop_column('users', 'activated')
    # ### end Alembic commands ###
